---
grails:
    profile: web
    codegen:
        defaultPackage: livelinessadmin
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
management:
    endpoints:
        jmx:
            unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false



dataSources:
    admin:
        pooled: true
        jmxExport: true
        driverClassName: com.mysql.jdbc.Driver
        username: remote
        password: '1234'

    liveliness:
        pooled: true
        jmxExport: true
        driverClassName: org.postgresql.Driver
        username: goyrkqdlmhyutc
        password: 'ee7432455d757046196ce598d14fc7f3d7af9371dc4ddf9758af0b9ad8af327e'
        url: jdbc:postgresql://ec2-107-21-122-38.compute-1.amazonaws.com/d6ho66lcuehn77

environments:
    development:
        dataSources:
            admin:
                dbCreate: create-drop
                url: jdbc:mysql://192.168.1.72:3306/LiveLinessAdmin
    test:
        dataSources:
            admin:
                dbCreate: update
                url: jdbc:mysql://192.168.1.72:3306/LiveLinessAdmin
    production:
        dataSources:
            admin:
                dbCreate: none
                url: jdbc:mysql://192.168.1.72:3306/LiveLinessAdmin
                properties:
                    jmxEnabled: true
                    initialSize: 5
                    maxActive: 50
                    minIdle: 5
                    maxIdle: 25
                    maxWait: 10000
                    maxAge: 600000
                    timeBetweenEvictionRunsMillis: 5000
                    minEvictableIdleTimeMillis: 60000
                    validationQuery: SELECT 1
                    validationQueryTimeout: 3
                    validationInterval: 15000
                    testOnBorrow: true
                    testWhileIdle: true
                    testOnReturn: false
                    jdbcInterceptors: ConnectionState
                    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

